---

- name: clone ffmpeg
  git: >
    repo=git://source.ffmpeg.org/ffmpeg.git
    accept_hostkey=true
    dest={{ ffmpeg_source_dir }}/ffmpeg
    version={{ ffmpeg_version }}

- name: compile ffmpeg
  environment: ffmpeg_env
  shell: 'cd {{ ffmpeg_source_dir }}/ffmpeg; {{ item }} creates={{ ffmpeg_bin_dir }}/ffmpeg'
  with_items:
    - ./configure {{ ffmpeg_flags }}
    - make -j {{ ffmpeg_make_jobs }}
    - make install{{ " DESTDIR=" + ffmpeg_install_dir if ffmpeg_install_dir else "" }}
    - "{{ 'make distclean' if ffmpeg_clean else '' }}"
