- name: clone latest speex
  git: >
    repo=https://git.xiph.org/speex.git
    accept_hostkey=true
    dest={{ ffmpeg_source_dir }}/speex
    version={{ ffmpeg_speex_version }}

- name: compile libspeex
  shell: 'cd {{ ffmpeg_source_dir }}/speex; {{ item }} creates={{ ffmpeg_build_dir }}/lib/libspeex.a'
  with_items:
    - libtoolize --force
    - aclocal
    - autoheader
    - automake --force-missing --add-missing
    - autoconf -i
    - ./configure --prefix={{ ffmpeg_build_dir }} --disable-shared
    - make -j {{ ffmpeg_make_jobs }}
    - make install
    - "{{ 'make distclean' if ffmpeg_clean else '' }}"
